version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    allow:
      - dependency-type: all   # includes direct and indirect dependencies

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
