version: 2
updates:
  - package-ecosystem: "bundler"
    directory: "/" # Location of package manifests
    schedule:
      interval: "daily"
    allow:
      - dependency-type: all   # includes direct and indirect dependencies
    groups:
      # Update rails dependencies together
      rails:
        patterns:
          - 'active*'

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
      interval: 'weekly'
