require:
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rspec.yml

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash']

RSpec/BeforeAfterAll:
  Enabled: false
