require:
  - rubocop-rspec
  - rubocop-performance

inherit_gem:
  rubocop-govuk:
    - config/default.yml
    - config/rspec.yml

AllCops:
  Exclude:
    - db/schema.rb

Style/EmptyElse:
  EnforcedStyle: empty

RSpec/ExampleLength:
  CountAsOne: ['array', 'hash']

RSpec/BeforeAfterAll:
  Enabled: false

# if you need it, you'll use it
RSpec/AnyInstance:
  Enabled: false
