version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - aws --version

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build . -t epb-register-api-worker -f sidekiq.Dockerfile

  post_build:
    commands:
      - echo Build completed on `date`
      - docker save -o epb-register-api-worker.tar epb-register-api-worker:latest

artifacts:
  files:
    - '**/*'


