version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - aws --version

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build . -t $DOCKER_IMAGE -f sidekiq.Dockerfile

  post_build:
    commands:
      - echo Build completed on `date`
      - docker save -o $DOCKER_IMAGE.tar $DOCKER_IMAGE:latest

artifacts:
  files:
    - '**/*'


