version: 0.2

phases:
  install:
    runtime-versions:
      docker: 19
  pre_build:
    commands:
      - aws --version

  build:
    commands:
      - echo Build started on `date`
      - echo Building the Docker image...
      - docker build -t $DOCKER_IMAGE_NAME ./
  post_build:
    commands:
      - echo Build completed on `date`
      - docker save -o $DOCKER_IMAGE_NAME.tar $DOCKER_IMAGE_NAME:latest

artifacts:
  files:
    - '**/*'


