version: 0.2

env:
  variables:
    DEPLOY_APPNAME: "epbr-register-api-integration"

phases:
  install:
    commands:
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2&
      - timeout 30 sh -c "until docker info; do echo .; sleep 1; done"


  build:
    commands:
      - echo Build started on `date`
      - echo Building the Paketo image...
      - pack build ebpr-register-api-image --builder paketobuildpacks/ubuntu-noble-builder

  post_build:
    commands:
      - echo Build completed on `date`
      - docker save -o $DOCKER_IMAGE.tar $DOCKER_IMAGE:latest

artifacts:
  files:
    - '**/*'
