version: 0.2

runtime-versions:
  ruby: 3.1

env:
  variables:
    DEPLOY_APPNAME: "mhclg-epb-register-api-staging"
    DEPLOY_WORKER: "dluhc-epb-worker-staging"
    EPB_API_DOCS_URL: "https://api-docs.epcregisters.net"

  parameter-store:
    PAAS_LOGIN: "epbr-govpaas-staging-login"
    PAAS_PW: "epbr-govpaas-staging-pw"
    PAAS_SPACE: "epbr-govpaas-staging-space"
    PAAS_API: "epbr-govpaas-api"
    PAAS_ORG: "epbr-govpaas-orgname"
    EPB_UNLEASH_URI: "epbr-unleash-staging-uri"
    EPB_UNLEASH_AUTH_TOKEN: "epbr-unleash-staging-auth-token"
    JWT_ISSUER: "epbr-jwt-issuer-staging"
    JWT_SECRET: "epbr-jwt-secret-staging"
    DOMESTIC_APPROVED_SOFTWARE: "software-versions-domestic-staging"
    NON_DOMESTIC_APPROVED_SOFTWARE: "software-versions-non-domestic-staging"
    SENTRY_DSN: "epbr-sentry-dsn-register-api"
    OS_DATA_HUB_API_KEY: "epbr-ordnance-survey-downloads-api-key"
    VALID_DOMESTIC_SCHEMAS: "epbr-schema-versions-domestic-staging"
    VALID_NON_DOMESTIC_SCHEMAS: "epbr-schema-versions-non-domestic-staging"
    EPB_TEAM_SLACK_URL: "epb-preproduction-slack-url"
    SLACK_EPB_BOT_TOKEN: "slack_epb_bot_outh_token"

phases:
  install:
    runtime-versions:
      ruby: 3.1
  pre_build:
    commands:
      - echo ">>>>>>>> DEPLOY TO STAGING ENV"
      - cf login -a $PAAS_API -u $PAAS_LOGIN -p "$PAAS_PW" -o $PAAS_ORG -s $PAAS_SPACE
      - cf cancel-deployment ${DEPLOY_APPNAME} || true
      - cf cancel-deployment ${DEPLOY_WORKER} || true
  build:
    commands:
      - make deploy-app
      - make migrate-db-and-wait-for-success
      - make deploy-worker
  post_build:
    commands:
      - cf logout
