version: 0.2

runtime-versions:
  ruby: 2.6

env:
  variables:
    DEPLOY_APPNAME: "mhclg-epb-register-api-production"

  parameter-store:
    PAAS_LOGIN: "epbr-govpaas-production-login"
    PAAS_PW: "epbr-govpaas-production-pw"
    PAAS_SPACE: "epbr-govpaas-production-space"
    PAAS_API: "epbr-govpaas-api"
    PAAS_ORG: "epbr-govpaas-orgname"
    EPB_UNLEASH_URI: "epbr-unleash-production-uri"
    JWT_ISSUER: "epbr-jwt-issuer-production"
    JWT_SECRET: "epbr-jwt-secret-production"
    NEW_RELIC_LICENSE_KEY: "epb-register-api-newrelic-licence"

phases:
  install:
    runtime-versions:
      ruby: 2.6
  pre_build:
    commands:
      - echo ">>>>>>>> DEPLOY TO PRODUCTION ENV"
      - cf login -a $PAAS_API -u $PAAS_LOGIN -p "$PAAS_PW" -o $PAAS_ORG -s $PAAS_SPACE
      - cf v3-cancel-zdt-push ${DEPLOY_APPNAME} || true
  build:
    commands:
      - make deploy-app
      - make migrate-db-and-wait-for-success
  post_build:
    commands:
      - cf logout
