version: 0.2

runtime-versions:
  ruby: 2.7

env:
  variables:
    DEPLOY_APPNAME: "mhclg-epb-register-api-integration"
    DEPLOY_WORKER: "mhclg-epb-worker-integration"

  parameter-store:
    PAAS_LOGIN: "epbr-govpaas-integration-login"
    PAAS_PW: "epbr-govpaas-integration-pw"
    PAAS_SPACE: "epbr-govpaas-integration-space"
    PAAS_API: "epbr-govpaas-api"
    PAAS_ORG: "epbr-govpaas-orgname"
    EPB_UNLEASH_URI: "epbr-unleash-integration-uri"
    EPB_UNLEASH_AUTH_TOKEN: "epbr-unleash-integration-auth-token"
    JWT_ISSUER: "epbr-jwt-issuer-integration"
    JWT_SECRET: "epbr-jwt-secret-integration"
    SENTRY_DSN: "epbr-sentry-dsn-register-api"

phases:
  install:
    runtime-versions:
      ruby: 2.7
  pre_build:
    commands:
      - echo ">>>>>>>> DEPLOY TO INTEGRATION ENV"
      - cf login -a $PAAS_API -u $PAAS_LOGIN -p "$PAAS_PW" -o $PAAS_ORG -s $PAAS_SPACE
      - cf cancel-deployment ${DEPLOY_APPNAME} || true
      - cf cancel-deployment ${DEPLOY_WORKER} || true
  build:
    commands:
      - make deploy-app
      - make migrate-db-and-wait-for-success
      - make deploy-worker
  post_build:
    commands:
      - cf logout
