openapi: 3.0.0

info:
  title: Energy Performance of Buildings Register API
  description: Public API for EPBR integrations
  version: 1.0.0-rc4

servers:
  - url: 'https://api.epb-integration.digital.communities.gov.uk/'
    description: Integration Service
  - url: 'https://api.epb-staging.digital.communities.gov.uk/'
    description: Staging Service
  - url: 'https://api.epb.digital.communities.gov.uk/'
    description: Production Service

tags:
  - name: Search
    description: Search the register given filtering data
  - name: Manage Assessors
    description: Manage assessors for a given Scheme
  - name: Manage Assessments
    description: 'Manage EPCs, DECs, RRs and ACIRs'
  - name: Manage Addresses
    description: Manage addresses in the register
  - name: Manage Schemes
    description: Operations for managing schemes in the register
  - name: Migration
    description: Endpoints used to migrate information from the legacy system
  - name: Green Deal
    description: Endpoints used by the Green Deal register integration, including Renewable Heat Initiative

paths:
  /schemes:
    get:
      tags:
        - Manage Schemes
      summary: Get a list of all energy assessment schemes in the register
      security:
        - oauth:
            - 'scheme:list'
    post:
      tags:
        - Manage Schemes
      summary: Add a new energy assessment scheme to the register
      security:
        - oauth:
            - 'scheme:create'
  '/schemes/{schemeId}/assessors':
    get:
      tags:
        - Manage Assessors
      summary: List a summary of assessors belonging to a scheme
      security:
        - oauth:
            - 'scheme:assessor:list'
  '/schemes/{schemeId}/assessors/{schemeAssessorId}':
    get:
      tags:
        - Manage Assessors
      summary: Get all details for an individual assessor registration
      security:
        - oauth:
            - 'scheme:assessor:fetch'
    put:
      tags:
        - Manage Assessors
      summary: >-
        Register a new assessor to associate them with your scheme,
        or update details of an assessor already on your scheme.
      security:
        - oauth:
            - 'scheme:assessor:update'
  /assessors:
    get:
      tags:
        - Search
        - Manage Assessors
      summary: Search for an assessor by postcode or name
      security:
        - oauth:
            - 'assessor:search'
  /search/addresses:
    get:
      tags:
        - Search
        - Manage Addresses
      summary: Search for an address by type and either a postcode or street and town
      security:
        - oauth:
            - 'search:addresses'
  '/assessments/{assessmentId}':
    get:
      tags:
        - Manage Assessments
      summary: Get an Energy Performance Assessment
      security:
        - oauth:
            - 'assessment:fetch'
  '/assessments/{assessmentType}/{assessmentId}':
    post:
      tags:
        - Manage Assessments
      summary: Lodge a new assessment
      security:
        - oauth:
            - 'assessment:lodge'
  /reports/assessors/status:
    get:
      tags:
        - Manage Assessors
        - Reports
      summary: >-
        Report of assessors who were suspended and struck off on a particular
        day
      security:
        - oauth:
            - 'report:assessor:status'
  '/migrations/assessors/{schemeAssessorId}':
    put:
      tags:
        - Migration
      summary: Migrate an assessor from the legacy database
      security:
        - oauth:
            - 'migrate:assessor'
  '/migrations/assessments/{assessmentId}':
    put:
      tags:
        - Migration
      summary: Migrate an existing Energy Performance Assessment to the register
      security:
        - oauth:
            - 'migrate:assessment'
  '/migrations/addresses/{addressId}':
    put:
      tags:
        - Migration
      summary: Migrate an address from AddressBase or another source of addresses
      security:
        - oauth:
            - 'migrate:address'
  '/greendeal/assessments/{assessmentId}':
    get:
      tags:
        - Green Deal
        summary: 'Get the Green Deal details from the assessment with reference
                  {assessmentId}'
      security:
        - oauth:
            - 'greendeal:assessment:fetch'
  '/greendeal/rhi/assessments/{assessmentId}/latest':
    get:
      tags:
        - Green Deal
      summary: 'Get the RHI details of the most recent Energy Performance
                Assessment for the address of the assessment with reference
                {assessmentId}'
      security:
        - oauth:
            - 'greendeal:assessment:fetch'
  '/greendeal/disclosure/plans/{assessmentId}':
    post:
      tags:
        - Green Deal
      summary: 'Disclose new live Green Deal plan to appear on EPC with RRN
                {assessmentId}'
      security:
        - oauth:
            - 'greendeal:disclosure:update'
components:
  securitySchemes:
    oauth:
      type: oauth2
      description: This API uses OAuth 2 with the client credentials grant flow
      flows:
        clientCredentials:
          tokenUrl: /auth/oauth/token
          scopes:
            'scheme:create': Create a new scheme on the register
            'scheme:list': List schemes on the register
            'scheme:assessor:list': List assessors
            'scheme:assessor:update': Add or Update assessors
            'scheme:assessor:fetch': Get full details of an individual assessor
            'assessment:fetch': Get full details of an individual assessment
            'assessment:lodge': Lodge a new assessment with the register
            'assessment:search': Search the register for an assessment
            'assessor:search': Search the register for an assessor
            'address:search': List addresses that match a given search criteria, along with existing assessments
            'migrate:assessment': Migrate an assessment to the register
            'migrate:assessor': Migrate an assessor to the register
            'migrate:address': Migrate an address to the register
            'report:assessor:status': Get a report of changes to assessors status for a given date
            'greendeal:assessment:fetch': Get limited details (RHI required fields) of an individual assessment
            'greendeal:disclosure:update': Submit or update details of a Green Deal Plan

security: []
