openapi: 3.0.0

info:
  title: Energy Performance of Buildings Register API
  description: Public API for EPBR integrations
  version: 1.0.0-rc4

servers:
  - url: 'https://api.epb-integration.digital.communities.gov.uk/api'
    description: Integration Service
  - url: 'https://api.epb-staging.digital.communities.gov.uk/api'
    description: Staging Service
  - url: 'https://api.epb.digital.communities.gov.uk/api'
    description: Production Service

tags:
  - name: Search
    description: Search the register given filtering data
  - name: Manage Assessors
    description: Manage assessors for a given Scheme
  - name: Manage Assessments
    description: Manage EPCs, DECs, RRs and AC-REPORTs
  - name: Manage Addresses
    description: Manage addresses in the register
  - name: Manage Schemes
    description: Operations for managing schemes in the register
  - name: Migration
    description: Endpoints used to migrate information from the legacy system
  - name: Green Deal
    description: Endpoints used by the Green Deal register integration, including Renewable Heat Initiative

paths:
  /schemes:
    get:
      tags:
        - Manage Schemes
      summary: Get a list of all energy assessment schemes in the register
      security:
        - oauth:
            - 'scheme:list'
    post:
      tags:
        - Manage Schemes
      summary: Add a new energy assessment scheme to the register
      security:
        - oauth:
            - 'scheme:create'
  /schemes/{schemeId}:
    put:
      tags:
        - Manage Schemes
      description: Update a scheme
  /schemes/{schemeId}/assessors:
    get:
      tags:
        - Manage Assessors
      summary: List a summary of assessors belonging to a scheme
      security:
        - oauth:
            - 'scheme:assessor:list'
  /schemes/{schemeId}/assessors/{schemeAssessorId}:
    get:
      tags:
        - Manage Assessors
      summary: Get all details for an individual assessor registration
      security:
        - oauth:
            - 'scheme:assessor:fetch'
    put:
      tags:
        - Manage Assessors
      summary: >-
        Register a new assessor to associate them with your scheme,
        or update details of an assessor already on your scheme.
      security:
        - oauth:
            - 'scheme:assessor:update'
  /assessors:
    get:
      tags:
        - Search
        - Manage Assessors
      summary: Search for an assessor by postcode or name
      security:
        - oauth:
            - 'assessor:search'
  /search/addresses:
    get:
      tags:
        - Search
        - Manage Addresses
      summary: 'Search for an address by (optional) type and
                EITHER:
                - a postcode (with optional building name or number)
                OR
                - a street AND town
                OR
                - a building reference number (UPRN or RRN)'
      security:
        - oauth:
            - 'search:addresses'
  /assessments/search:
    get:
      tags:
        - Search
        - Manage Assessments
      summary: Search for assessments
      description: 'Search for an assessment by
                    EITHER:
                     - a postcode AND assessment type
                    OR
                     - a street AND town AND assessment type
                    OR
                     - an assessment reference number (RRN)'
      security:
        - oauth:
            - 'assessment:search'
  /assessments:
    post:
      tags:
        - Manage Assessments
        - Migration
      summary: Lodge or migrate a new assessment
      description: 'Single endpoint for POSTing all new lodgements.
                    It will accept as XML payload:
                    * A single <Report> for a domestic RdSAP assessment
                    * A single <Report> for a domestic SAP assessment
                    * Non-domestic EPC and Recommendation report in a single XML
                      payload with two <Report> elements
                    * Air Conditioning certificate and AC-report in a single XML
                      payload with two <Report> elements
                    * A single <Report> for DEC
                    * A single <Report> for DEC recommendation report
                    * DEC and DEC-RR in a single XML payload with two <Report>
                      elements'
      security:
        - oauth:
            - 'assessment:lodge'
            - 'migrate:assessment'
  /assessments/{assessmentId}:
    get:
      tags:
        - Manage Assessments
      summary: Get an Energy Performance Assessment
      security:
        - oauth:
            - 'assessment:fetch'
  /assessments/{assessmentId}/summary:
    get:
      tags:
        - Manage Assessments
      summary: Get assessment details in use by frontend in JSON format
      security:
        - oauth:
          - 'assessment:fetch'
  /dec_summary/{assessmentId}:
    get:
      tags:
        - Manage Assessments
      summary: Get XML from DEC that can be used by AECOM software
      security:
        - oauth:
          - 'dec_summary:fetch'
  /assessments/{assessmentId}/status:
    post:
      tags:
        - Manage Assessments
      summary: Update the status of an assessment
      security:
        - oauth:
            - 'assessment:lodge'
  /reports/assessors/status:
    get:
      tags:
        - Manage Assessors
        - Reports
      summary: >-
        Report of assessors who were suspended and struck off on a particular
        day
      security:
        - oauth:
            - 'report:assessor:status'
  /migrations/assessors/{schemeAssessorId}:
    put:
      tags:
        - Migration
      summary: Migrate an assessor from the legacy database
      security:
        - oauth:
            - 'migrate:assessor'
  /migrations/addresses/{addressId}:
    put:
      tags:
        - Migration
      summary: Migrate an address from AddressBase or another source of addresses
      security:
        - oauth:
            - 'migrate:address'
  /greendeal/assessments/{assessmentId}:
    get:
      tags:
        - Green Deal
      summary: 'Get the Green Deal details from the assessment with reference
                {assessmentId}'
      security:
        - oauth:
            - 'greendeal:plans'
  /greendeal/assessments/{assessmentId}/xml:
    get:
      tags:
        - Green Deal
      summary: 'Get the redacted RdSAP XML for the assessment with reference
                {assessmentId}. The response will consist of redacted EPC XML
                that consists of the XML document as originally lodged, with the
                exception of the following redacted elements and their children:
                <Identification>
                <Configuration>
                <Calculation-Software-Name>
                <Calculation-Software-Version>
                <Inspection-Date>
                <Completion-Date>
                <Registration-Date>
                <Status>
                <Restricted-Access>
                <Transaction-Type>
                <Seller-Commission-Report>
                <Energy-Assessor>
                <Address>
                <Related-Party-Disclosure>
                <Insurance-Details>'
      security:
        - oauth:
            - 'greendeal:plans'
  /greendeal/rhi/assessments/{assessmentId}/latest:
    get:
      tags:
        - Green Deal
      summary: 'Get the RHI details of the most recent Energy Performance
                Assessment for the address of the assessment with reference
                {assessmentId}'
      security:
        - oauth:
            - 'greendeal:plans'
  /greendeal/disclosure/assessments/{assessmentId}/plans:
    post:
      tags:
        - Green Deal
      summary: 'Disclose new live Green Deal plan to appear on EPC with RRN
                {assessmentId}'
      security:
        - oauth:
            - 'greendeal:plans'
  /greendeal/disclosure/plans/{planId}:
    put:
      tags:
        - Green Deal
      summary: 'Update an existing Green Deal plan'
      security:
        - oauth:
            - 'greendeal:plans'
    delete:
      tags:
        - Green Deal
      summary: 'Delete an existing Green Deal plan'
      security:
        - oauth:
            - 'greendeal:plans'
  /reports/assessments/region-and-type:
    get:
      tags:
        - Reporting
      summary: 'Gets the data regarding matching postcodes to regions'
      security:
        - oauth:
            - 'reporting'
components:
  securitySchemes:
    oauth:
      type: oauth2
      description: This API uses OAuth 2 with the client credentials grant flow
      flows:
        clientCredentials:
          tokenUrl: /auth/oauth/token
          scopes:
            'scheme:create': Create a new scheme on the register
            'scheme:list': List schemes on the register
            'scheme:assessor:list': List assessors
            'scheme:assessor:update': Add or Update assessors
            'scheme:assessor:fetch': Get full details of an individual assessor
            'assessment:fetch': Get full details of an individual assessment
            'assessment:lodge': Lodge a new assessment with the register
            'assessment:search': Search the register for an assessment
            'assessor:search': Search the register for an assessor
            'address:search': List addresses that match a given search criteria, along with existing assessments
            'migrate:assessment': Migrate an assessment to the register
            'migrate:assessor': Migrate an assessor to the register
            'migrate:address': Migrate an address to the register
            'report:assessor:status': Get a report of changes to assessors status for a given date
            'greendeal:plans': Access all services necessary for the Green Deal register integration
