openapi: 3.0.0

info:
  title: Energy Performance of Buildings Register API
  description: Public API for EPBR integrations
  contact:
    name: DLUHC Digital helpdesk (prefix email subject with "EPB")
    email: dluhc.digital-services@levellingup.gov.uk
  version: 1.2.2

servers:
  - url: 'https://api.epb-integration.digital.communities.gov.uk/api'
    description: Integration Service
  - url: 'https://api.epb-staging.digital.communities.gov.uk/api'
    description: Staging Service
  - url: 'https://api.epb.digital.communities.gov.uk/api'
    description: Production Service

tags:
  - name: Search
    description: Search the register given filtering data
  - name: Manage Assessors
    description: Manage assessors for a given Scheme
  - name: Manage Assessments
    description: Manage EPCs, DECs, RRs and AC-REPORTs
  - name: Manage Schemes
    description: Operations for managing schemes in the register
  - name: Green Deal
    description: Endpoints used by the Green Deal register integration, including Renewable Heat Initiative
  - name: Boiler Upgrade Scheme
    description: Endpoints used by the Boiler Upgrade Scheme
  - name: Home Energy Retrofit Advice
    description: Endpoints used by the Home Energy Retrofit Advice service
  - name: Reports
    description: Endpoints providing reports, i.e. specific data views of operational interest
  - name: Service Performance
    description: Endpoints used in providing the Service Performance page

paths:
  /schemes:
    get:
      tags:
        - Manage Schemes
      summary: Get a list of all energy assessment schemes in the register
      description: List the energy assessment schemes
      operationId: list-schemes
      security:
        - oauth:
            - 'scheme:list'
    post:
      tags:
        - Manage Schemes
      summary: Add a new energy assessment scheme to the register
      description: Add an energy assessment scheme
      operationId: add-scheme
      security:
        - oauth:
            - 'scheme:create'
  /schemes/{schemeId}:
    put:
      tags:
        - Manage Schemes
      description: Update a scheme
      operationId: update-scheme
  /schemes/{schemeId}/assessors:
    get:
      tags:
        - Manage Assessors
      summary: List a summary of assessors belonging to a scheme
      description: List assessors for a scheme
      operationId: list-scheme-assessors
      security:
        - oauth:
            - 'scheme:assessor:list'
  /schemes/{schemeId}/assessors/{schemeAssessorId}:
    get:
      tags:
        - Manage Assessors
      summary: Get all details for an individual assessor registration
      description: Get details for an assessor on a scheme
      operationId: get-scheme-assessor
      security:
        - oauth:
            - 'scheme:assessor:fetch'
    put:
      tags:
        - Manage Assessors
      summary: >-
        Register a new assessor to associate them with your scheme,
        or update details of an assessor already on your scheme.
      description: Update or add an assessor
      operationId: upsert-assessor
      security:
        - oauth:
            - 'scheme:assessor:update'
  /assessors:
    get:
      tags:
        - Search
        - Manage Assessors
      summary: 'Search for an assessor by postcode or full name
                Clients with scope assessor:search can search by
                  EITHER:
                  - a postcode (with scope assessor:search) and optional qualification
                  OR
                  - full name (with scope assessor:search) and optional qualification type (domestic or non-domestic)

                Clients with scope scheme:assessor:fetch can search by
                  - firstName AND lastName AND dateOfBirth'
      description: Search for an assessor
      operationId: search-assessors
      security:
        - oauth:
            - 'assessor:search'
            - 'scheme:assessor:fetch'
  /search/addresses:
    get:
      tags:
        - Search
      summary: 'Search for an address by (optional) type and
                EITHER:
                - a postcode (with optional building name or number)
                OR
                - a street AND town
                OR
                - a building reference number (UPRN or RRN)'
      description: Search for usable addresses for an assessment
      operationId: search-addresses
      security:
        - oauth:
            - 'search:addresses'
  /assessments/search:
    get:
      tags:
        - Search
        - Manage Assessments
      summary: Search for assessments
      description: 'Search for an assessment by
                    EITHER:
                     - a postcode AND assessment type
                    OR
                     - a street AND town AND assessment type
                    OR
                     - an assessment reference number (RRN)'
      operationId: search-assessments
      security:
        - oauth:
            - 'assessment:search'
  /assessments/domestic-epcs/search:
    get:
      tags:
        - Search
        - Home Energy Retrofit Advice
      summary: Search for domestic EPCs by address
      description: 'Search for an assessment by postcode and optional building name/number.
                    If building name/number is supplied and no matches are found
                    or building name/number is not supplied
                    then all domestic EPC matches for the postcode are returned'
      operationId: search-domestic-epcs
      security:
        - oauth:
            - 'assessment:domestic-epc:search'
  /assessments:
    post:
      tags:
        - Manage Assessments
      summary: Lodge a new assessment or migrate an existing assessment
      description: 'Single endpoint for POSTing all new lodgements.
                    It will accept as XML payload:
                    * A single <Report> for a domestic RdSAP assessment
                    * A single <Report> for a domestic SAP assessment
                    * Non-domestic EPC and Recommendation report in a single XML
                      payload with two <Report> elements
                    * Air Conditioning certificate and AC-report in a single XML
                      payload with two <Report> elements
                    * A single <Report> for DEC
                    * A single <Report> for DEC recommendation report
                    * DEC and DEC-RR in a single XML payload with two <Report>
                      elements'
      operationId: lodge-assessment
      security:
        - oauth:
            - 'assessment:lodge'
            - 'migrate:assessment'
  /assessments/{assessmentId}:
    get:
      tags:
        - Manage Assessments
      summary: Get an Energy Performance Assessment
      description: Get an assessment's XML
      operationId: get-assessment-xml
      security:
        - oauth:
            - 'assessment:fetch'
  /assessments/{assessmentId}/summary:
    get:
      tags:
        - Manage Assessments
      summary: Get assessment details in use by frontend in JSON format
      description: Get summary of assessment for use by frontend
      operationId: get-assessment-summary
      security:
        - oauth:
            - 'assessment:fetch'
  /assessments/{assessmentId}/meta-data:
    get:
      tags:
        - Manage Assessments
      summary: Get assessment metadata attributes used by data-warehouse in JSON format
      description: Get assessment metadata
      operationId: get-assessment-metadata
      security:
        - oauth:
            - 'assessmentmetadata:fetch'
  /assessments/{assessmentId}/opt-out:
    put:
      tags:
        - Manage Assessments
      summary: Mark an assessment as opted in or out from search and open data publication
      description: Update opt-out status of an assessment
      operationId: update-assessment-optout-status
      security:
        - oauth:
            - 'admin:opt_out'
  /assessments/{assessmentId}/address-id:
    put:
      tags:
        - Manage Assessments
      summary: Update the address ID used to link this assessment with other assessments
      description: Update the canonical address ID for an assessment
      operationId: update-canonical-address-id
      security:
        - oauth:
            - 'admin:update-address-id'
  /dec_summary/{assessmentId}:
    get:
      tags:
        - Manage Assessments
      summary: Get XML from DEC that can be used by AECOM software
      description: Get the XML for a DEC
      operationId: get-dec-xml
      security:
        - oauth:
            - 'dec_summary:fetch'
  /assessments/{assessmentId}/status:
    post:
      tags:
        - Manage Assessments
      summary: Update the status of an assessment
      description: Update assessment status
      operationId: update-assessment-status
      security:
        - oauth:
            - 'assessment:lodge'
  /reports/{schemeId}/assessors/status:
    get:
      tags:
        - Manage Assessors
        - Reports
      summary: >-
        Report of assessors who were suspended and struck off on a particular
        day filtered by matching a last name and date of birth to an assessor registered by the queuing scheme
      description: Get report of assessors who were struck off on a particular day
      operationId: get-assessor-status-report
      security:
        - oauth:
            - 'report:assessor:status'
  /bus/assessments/latest/search:
    get:
      tags:
        - Boiler Upgrade Scheme
      summary: Search for assessments exposing details for the Boiler Upgrade Scheme (BUS)
      description: 'Search for an assessment by
                    EITHER
                     - a postcode AND building name/ number
                    OR
                     - an address ID (UPRN)
                    OR
                     - an assessment reference number (RRN)
                     in each case returning the BUS details of the most recent
                     Energy Performance Certificate (EPC) for the property'
      operationId: bus-search-latest-assessments
      security:
        - oauth:
            - 'bus:assessment:search'
  /retrofit-advice/assessments/{assessmentId}:
    get:
      tags:
        - Home Energy Retrofit Advice
      summary: 'Get the Home Energy Retrofit Advice details from the domestic EPC
                with reference {assessmentId}'
      description: Get domestic EPC details for the supplied RRN
      operationId: get-assessment-retrofit-advice
      security:
        - oauth:
            - 'retrofit-advice:assessment:fetch'
  /greendeal/assessments/{assessmentId}:
    get:
      tags:
        - Green Deal
      summary: 'Get the Green Deal details from the assessment with reference
                {assessmentId}'
      description: Get any Green Deals against an assessment
      operationId: get-assessment-green-deals
      security:
        - oauth:
            - 'greendeal:plans'
  /greendeal/assessments/{assessmentId}/xml:
    get:
      tags:
        - Green Deal
      summary: 'Get the redacted RdSAP XML for the assessment with reference
                {assessmentId}. The response will consist of redacted EPC XML
                that consists of the XML document as originally lodged, with the
                exception of the following redacted elements and their children:
                <Identification>
                <Configuration>
                <Calculation-Software-Name>
                <Calculation-Software-Version>
                <Inspection-Date>
                <Completion-Date>
                <Registration-Date>
                <Status>
                <Restricted-Access>
                <Transaction-Type>
                <Seller-Commission-Report>
                <Energy-Assessor>
                <Address>
                <Related-Party-Disclosure>
                <Insurance-Details>'
      description: Get RdSAP assessment XML with sensitive nodes redacted
      operationId: get-redacted-assessment-xml
      security:
        - oauth:
            - 'greendeal:plans'
  /greendeal/rhi/assessments/{assessmentId}/latest:
    get:
      tags:
        - Green Deal
      summary: 'Get the RHI details of the most recent Energy Performance
                Assessment for the address of the assessment with reference
                {assessmentId}'
      description: Get RHI details for assessment address's most recent assessment
      operationId: get-latest-rhi
      security:
        - oauth:
            - 'greendeal:plans'
  /greendeal/disclosure/assessments/{assessmentId}/plans:
    post:
      tags:
        - Green Deal
      summary: 'Disclose new live Green Deal plan to appear on EPC with RRN
                {assessmentId}'
      description: Accept disclosure of new live Green Deal plan against assessment
      operationId: accept-green-deal-disclosure
      security:
        - oauth:
            - 'greendeal:plans'
  /greendeal/disclosure/plans/{planId}:
    put:
      tags:
        - Green Deal
      summary: 'Update an existing Green Deal plan'
      description: Update a Green Deal plan
      operationId: update-green-deal-plan
      security:
        - oauth:
            - 'greendeal:plans'
    delete:
      tags:
        - Green Deal
      summary: 'Delete an existing Green Deal plan'
      description: Delete an existing Green Deal plan
      operationId: delete-green-deal-plan
      security:
        - oauth:
            - 'greendeal:plans'
  /reports/assessments/region-and-type:
    get:
      tags:
        - Reports
      summary: 'Gets the data regarding matching postcodes to regions'
      description: Get region and type assessment data
      operationId: get-region-and-type-report
      security:
        - oauth:
            - 'reporting:assessment_by_type_and_region'
  /reports/assessments/scheme-and-type:
    get:
      tags:
        - Reports
      summary: >-
        Creates a report of the number of assessments lodged between
        two dates broken down by assessment type and lodging scheme
      description: Get report of assessment counts split by type and scheme
      operationId: get-assessment-counts-by-scheme-and-type-report
      security:
        - oauth:
            - 'reporting:assessment_by_scheme_and_type'
  /reports/assessments/scheme-and-type/rrn:
    get:
      tags:
        - Reports
      summary: >-
        Creates a report of lodgements made by each assessor scheme used for invoicing
      description: Get a report of lodgements by scheme
      operationId: get-assessments-by-scheme-report
      security:
        - oauth:
            - 'reporting:assessment_by_scheme_and_type'
  /statistics:
    get:
      tags:
        - Service Performance
      summary: >-
        Fetch the statistics data displayed on the Service Performance page
      description: Get statistics data for EPCs
      operationId: get-assessment-statistics-data
      security:
        - oauth:
            - 'statistics:fetch'
  /user-satisfaction:
    put:
      tags:
        - Service Performance
      summary: Add user satisfaction data for a month, for display on the Service Performance page
      description: Update user satisfaction
      operationId: put-user-satisfaction
      security:
        - oauth:
            - 'admin:upload_stats'
components:
  securitySchemes:
    oauth:
      type: oauth2
      description: This API uses OAuth 2 with the client credentials grant flow
      flows:
        clientCredentials:
          tokenUrl: /auth/oauth/token
          scopes:
            'scheme:create': Create a new scheme on the register
            'scheme:list': List schemes on the register
            'scheme:assessor:list': List assessors
            'scheme:assessor:update': Add or Update assessors
            'scheme:assessor:fetch': Get full details of an individual assessor
            'assessment:fetch': Get full details of an individual assessment
            'assessmentmetadata:fetch': Get the additional attributes we require for assessments
            'assessment:lodge': Lodge a new assessment with the register
            'assessment:search': Search the register for an assessment
            'assessor:search': Search the register for an assessor
            'address:search': List addresses that match a given search criteria, along with existing assessments
            'migrate:assessment': Migrate an assessment to the register
            'report:assessor:status': Get a report of changes to assessors status for a given date
            'greendeal:plans': Access all services necessary for the Green Deal register integration
            'bus:assessment:search': Carry out Boiler Upgrade Scheme search for latest EPC data
            'retrofit-advice:assessment:fetch': Carry out Home Energy Retrofit Advice search for latest domestic EPC data
