name: Database Offline Backup

on:
  schedule: # 03:00 UTC
    - cron: '0 3 * * *'
  workflow_dispatch:
    inputs:

jobs:
  backup:
    name: Restore Production Database To New Service
    runs-on: ubuntu-latest

    steps:
      - uses: DFE-Digital/bat-infrastructure/actions/setup-cf-cli@main
        name: Setup cf cli
        with:
          CF_USERNAME: ${{ secrets.CF_USERNAME_INTEGRATION }}
          CF_PASSWORD: ${{ secrets.CF_PASSWORD_INTEGRATION }}
          CF_SPACE_NAME: integration
          INSTALL_CONDUIT: true

      - name: Set Environment
        run: |
          echo "app_guid=\"$(cf app $mhclg-epb-register-api-integration --guid)\"" >> $GITHUB_ENV

      - name: Read Env
        run: env
