name: Lint and test

on:
  pull_request:
  push:
    branches:
      - master

permissions:
  contents: read

env:
  DATABASE_URL: postgresql://postgres:postgres@127.0.0.1/epb_test

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:18
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v5
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
      - name: Setup database
        run: make setup-db
      - name: Lint
        run: make lint
      - name: Test
        run: make test
